env:
  global:
    - CC_TEST_REPORTER_ID: "73226daa262de1c4ef28ac50be0b48c2b512b763a1a5aa33d3276a2a8ccd0e98"
language: node_js
node_js:
  - 6.10.0
cache:
  directories:
    - node_modules
branches:
  only:
  - develop
addons:
  jwt:
    secure: "zxerth5603UHdjdjdndblepocnvbehwocvvjisjkvdkohschcaxzsawagdchdcxfscvfdsyhxbxgsdbv"
  code_climate:
    repo_token: "73226daa262de1c4ef28ac50be0b48c2b512b763a1a5aa33d3276a2a8ccd0e98"
script:
  - npm test
before_script:
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'create database travis;' -U postgres
after_script:
  - npm run coverage
services:
  - postgresql